//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Helpdesk {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Translation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Helpdesk.Translation", typeof(Translation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account created! You can now sign in..
        /// </summary>
        internal static string account_created {
            get {
                return ResourceManager.GetString("account_created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthdate.
        /// </summary>
        internal static string birth_text {
            get {
                return ResourceManager.GetString("birth_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat.
        /// </summary>
        internal static string confirm_text {
            get {
                return ResourceManager.GetString("confirm_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        internal static string email_text {
            get {
                return ResourceManager.GetString("email_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email is already used.
        /// </summary>
        internal static string email_used_message {
            get {
                return ResourceManager.GetString("email_used_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        internal static string firstName_text {
            get {
                return ResourceManager.GetString("firstName_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Housenum..
        /// </summary>
        internal static string housenum_text {
            get {
                return ResourceManager.GetString("housenum_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infix.
        /// </summary>
        internal static string infix_text {
            get {
                return ResourceManager.GetString("infix_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        internal static string lastName_text {
            get {
                return ResourceManager.GetString("lastName_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged in as customer.
        /// </summary>
        internal static string logged_in_customer {
            get {
                return ResourceManager.GetString("logged_in_customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged in as staff member.
        /// </summary>
        internal static string logged_in_staff {
            get {
                return ResourceManager.GetString("logged_in_staff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        internal static string login_button {
            get {
                return ResourceManager.GetString("login_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed.
        /// </summary>
        internal static string login_failed {
            get {
                return ResourceManager.GetString("login_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or password incorrect, try again.
        /// </summary>
        internal static string login_failed_message {
            get {
                return ResourceManager.GetString("login_failed_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        internal static string login_page {
            get {
                return ResourceManager.GetString("login_page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age not allowed.
        /// </summary>
        internal static string minimum_age_caption {
            get {
                return ResourceManager.GetString("minimum_age_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to be 18 years old to create an account.
        /// </summary>
        internal static string minimum_age_message {
            get {
                return ResourceManager.GetString("minimum_age_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No account yet?.
        /// </summary>
        internal static string no_account_question {
            get {
                return ResourceManager.GetString("no_account_question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string password_text {
            get {
                return ResourceManager.GetString("password_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phonenumber.
        /// </summary>
        internal static string phone_text {
            get {
                return ResourceManager.GetString("phone_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Residence.
        /// </summary>
        internal static string place_text {
            get {
                return ResourceManager.GetString("place_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postalcode.
        /// </summary>
        internal static string postal_text {
            get {
                return ResourceManager.GetString("postal_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string register_title {
            get {
                return ResourceManager.GetString("register_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        internal static string registerButton {
            get {
                return ResourceManager.GetString("registerButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street.
        /// </summary>
        internal static string street_text {
            get {
                return ResourceManager.GetString("street_text", resourceCulture);
            }
        }
    }
}
