//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Helpdesk {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Translation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Helpdesk.Translation", typeof(Translation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account created! You can now sign in..
        /// </summary>
        internal static string account_created {
            get {
                return ResourceManager.GetString("account_created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Staff.
        /// </summary>
        internal static string add_staff {
            get {
                return ResourceManager.GetString("add_staff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string add_text {
            get {
                return ResourceManager.GetString("add_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthdate.
        /// </summary>
        internal static string birth_text {
            get {
                return ResourceManager.GetString("birth_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        internal static string change_button {
            get {
                return ResourceManager.GetString("change_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes saved.
        /// </summary>
        internal static string changes_saved {
            get {
                return ResourceManager.GetString("changes_saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat.
        /// </summary>
        internal static string confirm_text {
            get {
                return ResourceManager.GetString("confirm_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string delete_text {
            get {
                return ResourceManager.GetString("delete_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Staff.
        /// </summary>
        internal static string edit_staff {
            get {
                return ResourceManager.GetString("edit_staff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string edit_text {
            get {
                return ResourceManager.GetString("edit_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        internal static string email_text {
            get {
                return ResourceManager.GetString("email_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email is already used.
        /// </summary>
        internal static string email_used_message {
            get {
                return ResourceManager.GetString("email_used_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First login.
        /// </summary>
        internal static string first_login {
            get {
                return ResourceManager.GetString("first_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        internal static string firstName_text {
            get {
                return ResourceManager.GetString("firstName_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed telephony.
        /// </summary>
        internal static string fixed_telephony {
            get {
                return ResourceManager.GetString("fixed_telephony", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helpdesk personel.
        /// </summary>
        internal static string helpdesk_staff {
            get {
                return ResourceManager.GetString("helpdesk_staff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Housenum..
        /// </summary>
        internal static string housenum_text {
            get {
                return ResourceManager.GetString("housenum_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infix.
        /// </summary>
        internal static string infix_text {
            get {
                return ResourceManager.GetString("infix_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoices.
        /// </summary>
        internal static string invoices {
            get {
                return ResourceManager.GetString("invoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT professional.
        /// </summary>
        internal static string IT_staff {
            get {
                return ResourceManager.GetString("IT_staff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        internal static string lastName_text {
            get {
                return ResourceManager.GetString("lastName_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged in as customer.
        /// </summary>
        internal static string logged_in_customer {
            get {
                return ResourceManager.GetString("logged_in_customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged in as IT professional.
        /// </summary>
        internal static string logged_in_ict {
            get {
                return ResourceManager.GetString("logged_in_ict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged in as staff member.
        /// </summary>
        internal static string logged_in_staff {
            get {
                return ResourceManager.GetString("logged_in_staff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        internal static string login_button {
            get {
                return ResourceManager.GetString("login_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed.
        /// </summary>
        internal static string login_failed {
            get {
                return ResourceManager.GetString("login_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or password incorrect, try again.
        /// </summary>
        internal static string login_failed_message {
            get {
                return ResourceManager.GetString("login_failed_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        internal static string login_page {
            get {
                return ResourceManager.GetString("login_page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age not allowed.
        /// </summary>
        internal static string minimum_age_caption {
            get {
                return ResourceManager.GetString("minimum_age_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to be 18 years old to create an account.
        /// </summary>
        internal static string minimum_age_message {
            get {
                return ResourceManager.GetString("minimum_age_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile telephony.
        /// </summary>
        internal static string mobile_telephony {
            get {
                return ResourceManager.GetString("mobile_telephony", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        internal static string new_password {
            get {
                return ResourceManager.GetString("new_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No account yet?.
        /// </summary>
        internal static string no_account_question {
            get {
                return ResourceManager.GetString("no_account_question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string none {
            get {
                return ResourceManager.GetString("none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string other {
            get {
                return ResourceManager.GetString("other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password changed.
        /// </summary>
        internal static string password_changed_caption {
            get {
                return ResourceManager.GetString("password_changed_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password doesn&apos;t meet the requirements.
        /// </summary>
        internal static string password_doesnt_meet {
            get {
                return ResourceManager.GetString("password_doesnt_meet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - At least 8 characters.
        /// </summary>
        internal static string password_eight_characters {
            get {
                return ResourceManager.GetString("password_eight_characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match.
        /// </summary>
        internal static string password_no_match {
            get {
                return ResourceManager.GetString("password_no_match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - At least 1 digit.
        /// </summary>
        internal static string password_one_digit {
            get {
                return ResourceManager.GetString("password_one_digit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - At least 1 lowercase character.
        /// </summary>
        internal static string password_one_lower {
            get {
                return ResourceManager.GetString("password_one_lower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - At least 1 special character.
        /// </summary>
        internal static string password_one_special {
            get {
                return ResourceManager.GetString("password_one_special", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - At least 1 uppercase character.
        /// </summary>
        internal static string password_one_upper {
            get {
                return ResourceManager.GetString("password_one_upper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password doesn&apos;t meet the following requirements:.
        /// </summary>
        internal static string password_strong_message {
            get {
                return ResourceManager.GetString("password_strong_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string password_text {
            get {
                return ResourceManager.GetString("password_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phonenumber.
        /// </summary>
        internal static string phone_text {
            get {
                return ResourceManager.GetString("phone_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Residence.
        /// </summary>
        internal static string place_text {
            get {
                return ResourceManager.GetString("place_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postalcode.
        /// </summary>
        internal static string postal_text {
            get {
                return ResourceManager.GetString("postal_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prices.
        /// </summary>
        internal static string prices {
            get {
                return ResourceManager.GetString("prices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string register_title {
            get {
                return ResourceManager.GetString("register_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        internal static string registerButton {
            get {
                return ResourceManager.GetString("registerButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job.
        /// </summary>
        internal static string role_text {
            get {
                return ResourceManager.GetString("role_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : .
        /// </summary>
        internal static string semicolon {
            get {
                return ResourceManager.GetString("semicolon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specialism.
        /// </summary>
        internal static string specialism_text {
            get {
                return ResourceManager.GetString("specialism_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff added with password: .
        /// </summary>
        internal static string staff_added_1 {
            get {
                return ResourceManager.GetString("staff_added_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///The password has been copied..
        /// </summary>
        internal static string staff_added_2 {
            get {
                return ResourceManager.GetString("staff_added_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New account created.
        /// </summary>
        internal static string staff_added_header {
            get {
                return ResourceManager.GetString("staff_added_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        internal static string staff_delete_caption {
            get {
                return ResourceManager.GetString("staff_delete_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this account?
        ///This action is irreversable..
        /// </summary>
        internal static string staff_delete_message {
            get {
                return ResourceManager.GetString("staff_delete_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff.
        /// </summary>
        internal static string staff_text {
            get {
                return ResourceManager.GetString("staff_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street.
        /// </summary>
        internal static string street_text {
            get {
                return ResourceManager.GetString("street_text", resourceCulture);
            }
        }
    }
}
